var segment_samples = [{video:"v_tFgbKk7n_IE", classname:"Breakdancing"},
{video:"v_5TkSK0l0pVg", classname:"Washing hands"},
{video:"v_Ytfl0vYgNBY", classname:"Arm wrestling"},
{video:"v_iZ1w_EvCraU", classname:"Chopping wood"},
{video:"v_jxXvvxnlkog", classname:"Swinging at the playground"},
{video:"v_254XsvRC5t4", classname:"Waxing skis"},
{video:"v_AmvF52foyCs", classname:"Shot put"},
{video:"v_drrMac-ed-E", classname:"Clean and jerk"},
{video:"v_R88BTkff1xA", classname:"Horseback riding"},
{video:"v_dAiV57SCqUQ", classname:"Chopping wood"},
{video:"v_BUZi52Lk3Xc", classname:"Hand washing clothes"},
{video:"v_1TpN61UHZrw", classname:"Rollerblading"},
{video:"v_FRCBTcnW8sg", classname:"Ballet"},
{video:"v_G__wv_CJVns", classname:"Calf roping"},
{video:"v_7DK4Gtv9XDA", classname:"Playing drums"},
{video:"v_NCzsyAFu7pI", classname:"Smoking a cigarette"},
{video:"v_6sTDTYBw25o", classname:"Pole vault"},
{video:"v_GnoTZ7ZMg90", classname:"Pole vault"},
{video:"v_mOiFYqi4El4", classname:"Playing ten pins"},
{video:"v_HQI-PP6G9aI", classname:"Bathing dog"},
{video:"v_wB-9Z9miqGg", classname:"Ping-pong"},
{video:"v_kuJBox3Xb3Q", classname:"Snatch"},
{video:"v_tr3yzC9zCKY", classname:"Rope skipping"},
{video:"v_5ikBRkmu-c8", classname:"Canoeing"},
{video:"v_FqELTsDQWhk", classname:"Throwing darts"},
{video:"v_c9i8e4td_X8", classname:"Wakeboarding"},
{video:"v_BXQDel0cFsM", classname:"Playing piano"},
{video:"v_jeJETuiLPBo", classname:"Mowing the lawn"},
{video:"v_GV0Vuk1NOK0", classname:"High jump"},
{video:"v_sU2iUJLo034", classname:"Blowing leaves"},
{video:"v_huPmf7oZHjU", classname:"BMX"},
{video:"v_SArZOF83EyQ", classname:"Javelin throw"},
{video:"v_tAEv_bYm_Ro", classname:"Tennis serve with ball bouncing"},
{video:"v_AuEdwMa6qSo", classname:"Carving jack-o-lanterns"},
{video:"v_OZhJ1BmrErM", classname:"Spread mulch"},
{video:"v_iSfRnZPxwBY", classname:"Fun sliding down"},
{video:"v_5rvcPIzWJv0", classname:"Layup drill in basketball"},
{video:"v_7_xkhnbnI7M", classname:"Clipping cat claws"},
{video:"v_3-AM7JvNBcU", classname:"Playing water polo"},
{video:"v_RfuxscmpzSw", classname:"Playing congas"},
{video:"v_zHszIxZG7go", classname:"Slacklining"},
{video:"v_P97PuL0hLOg", classname:"Mixing drinks"},
{video:"v_wnDSM3FZBtA", classname:"Mixing drinks"},
{video:"v_Jnl1K7l5OVQ", classname:"Cheerleading"},
{video:"v_crvR-cm5IbE", classname:"High jump"},
{video:"v_oz2HIYkJh6k", classname:"Carving jack-o-lanterns"},
{video:"v_L2otSq4m9Uw", classname:"Carving jack-o-lanterns"},
{video:"v_T2E8ecb4xso", classname:"Wrapping presents"},
{video:"v_0f5sP19MS0Q", classname:"Using parallel bars"},
{video:"v_nY9kYrLtYAM", classname:"Washing dishes"},
{video:"v_biR-rO6MuZ0", classname:"Smoking hookah"},
{video:"v_xELv31S46hM", classname:"Skiing"},
{video:"v_9SJYi12e-e4", classname:"BMX"},
{video:"v_QBAXGv3Xi4o", classname:"Springboard diving"},
{video:"v_ckpS5pKbw9c", classname:"Cleaning shoes"},
{video:"v_zOIvs2q_8Q8", classname:"Hurling"},
{video:"v_gv7_WEJrQvk", classname:"Doing fencing"},
{video:"v_Fs2qyZoPjc4", classname:"Wakeboarding"},
{video:"v_mkcHEOz53I0", classname:"Javelin throw"},
{video:"v_vQ8kxU8xDak", classname:"Cleaning shoes"},
{video:"v_jkiOj-6Slg0", classname:"Clipping cat claws"},
{video:"v_qq0rvd14LQs", classname:"Decorating the Christmas tree"},
{video:"v_dIoxI5soBX4", classname:"Cleaning shoes"},
{video:"v_h8dTxm-2dkM", classname:"Carving jack-o-lanterns"},
{video:"v_Rxtgle8JUpM", classname:"Knitting"},
{video:"v_fUsGtbKeJik", classname:"Decorating the Christmas tree"},
{video:"v_Mn4DRcK9zO4", classname:"Shot put"},
{video:"v_xjQwhcu8iXA", classname:"BMX"},
{video:"v_JUdi-8V8zOg", classname:"Tango"},
{video:"v_EDk0VvmTPqU", classname:"Snow tubing"},
{video:"v_7dJm1LwLLdk", classname:"Waxing skis"},
{video:"v_wZI0ifu5dMA", classname:"Getting a piercing"},
{video:"v_n6glrknxlrY", classname:"Hand car wash"},
{video:"v_qnBbG5Nahzo", classname:"Slacklining"},
{video:"v_bUZBELsXMME", classname:"Raking leaves"},
{video:"v_cmvWmrRY7Kk", classname:"Canoeing"},
{video:"v_2evkTNy1fGo", classname:"Skateboarding"},
{video:"v_yA99v9k1U24", classname:"Mixing drinks"},
{video:"v_NJQ10otmK9A", classname:"Wakeboarding"},
{video:"v_qdCSLOBLKm4", classname:"Having an ice cream"},
{video:"v_oAbN5J9FOnE", classname:"Doing fencing"},
{video:"v_T_bDga-DM7Y", classname:"Javelin throw"},
{video:"v_ouBch58AXK4", classname:"Playing pool"},
{video:"v_UL-3rBwPqBM", classname:"Cheerleading"},
{video:"v_CQtmOk19jT0", classname:"Playing ten pins"},
{video:"v_fn2V4v10Z9U", classname:"Scuba diving"},
{video:"v_beSqAn0jjwU", classname:"Kayaking"},
{video:"v_6YfqbKdb9bo", classname:"Kayaking"},
{video:"v_fcyGIdtfY2Q", classname:"Windsurfing"},
{video:"v_7Ej8-W_L8bM", classname:"Raking leaves"},
{video:"v_V8zBauCN2j8", classname:"Slacklining"},
{video:"v_-B1f6lxWdV8", classname:"Playing ice hockey"},
{video:"v_n9DQEejXDXs", classname:"Playing piano"},
{video:"v_hTmnxmr32ZU", classname:"Clipping cat claws"},
{video:"v_Dr8WieoCOeI", classname:"Knitting"},
{video:"v_moquzf48zCM", classname:"Rafting"},
{video:"v_OgBC-jj7C90", classname:"Playing drums"},
{video:"v_8eTqwR7E6As", classname:"Cutting the grass"},
{video:"v_iCND1oi_pNw", classname:"Canoeing"},
{video:"v_XmZs5eCkbHk", classname:"Playing pool"},
{video:"v_5BONaGwYVVU", classname:"Gargling mouthwash"},
{video:"v_Mgt7VjYNLTk", classname:"Playing congas"},
{video:"v_PiG2Buji6K8", classname:"Spread mulch"},
{video:"v_7p1WMvDiNi4", classname:"Sharpening knives"},
{video:"v_0BrSKoBSZt0", classname:"Throwing darts"},
{video:"v_VGJymXQI1RE", classname:"Doing fencing"},
{video:"v_YZM8B4c2pT4", classname:"Canoeing"},
{video:"v_2RMjtisLpsY", classname:"Kayaking"},
{video:"v_YZhtAJ7VtTI", classname:"Hula hoop"},
{video:"v_VR9QD7GjimM", classname:"Snowboarding"},
{video:"v_jmnr0sGyPfw", classname:"Putting in contact lenses"},
{video:"v_kGSYVf61ZwI", classname:"Wakeboarding"},
{video:"v_eaWa2RkbPik", classname:"Playing congas"},
{video:"v_0521Nsc2RbA", classname:"Using the balance beam"},
{video:"v_b4wzLE-Q9Z8", classname:"Mowing the lawn"},
{video:"v_u_5CH5T2T9Y", classname:"Shaving legs"},
{video:"v_ZFaoZWU31zU", classname:"Bullfighting"},
{video:"v_9bffMqnkE_4", classname:"Long jump"},
{video:"v_Z1Gv0fId-rQ", classname:"Fun sliding down"},
{video:"v_2Iztn3by2Bk", classname:"Chopping wood"},
{video:"v_EGBUYWAvcSg", classname:"Pole vault"},
{video:"v_yTXbObM14cE", classname:"Cricket"},
{video:"v_XR1be_hVrQI", classname:"Sailing"},
{video:"v_f8E3lPF6iK8", classname:"Cricket"},
{video:"v_g88_z9wcnUo", classname:"Ping-pong"},
{video:"v_JCrjx4joHxI", classname:"Knitting"},
]; 